<?php
$value = array (
  'wwwprefix' => '',
  'imgprefix' => '',
  'cssprefix' => '',
  'sitename' => '邻客美国',
  'sitetitle' => '你的美国娱乐攻略',
  'abbreviation' => '邻客美国',
  'couponname' => '优惠券',
  'currency' => '$',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'editor' => 'kind',
  'indexteam' => '0',
  'sideteam' => '0',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '329975604',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'kefu_hotline' => '020-123456',
  'server_time' => '9:00-18:00',
  'tousu_email' => '4545565@bn.com',
);
?>
